# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class Experiment_APIStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RPC = channel.unary_unary(
                '/Experiment_API/RPC',
                request_serializer=api__pb2.RPC_Request.SerializeToString,
                response_deserializer=api__pb2.RPC_Reply.FromString,
                )


class Experiment_APIServicer(object):
    """Missing associated documentation comment in .proto file"""

    def RPC(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Experiment_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RPC': grpc.unary_unary_rpc_method_handler(
                    servicer.RPC,
                    request_deserializer=api__pb2.RPC_Request.FromString,
                    response_serializer=api__pb2.RPC_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Experiment_API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Experiment_API(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def RPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Experiment_API/RPC',
            api__pb2.RPC_Request.SerializeToString,
            api__pb2.RPC_Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
