version: '3.1'
services:
  web:
    build: nginx
    ports:
      - "8080:80"
    depends_on:
      - application
    links:
      - application
    networks:
      - default
      - frontend
    security_opt:
      - no-new-privileges
  application:
    build: .
    depends_on:
      - database
      - worker
    links:
      - database
    networks:
      - frontend
      - backend
    volumes:
      - rpc_channels:/var/run/cryptomato
      - prisma_migrations:/usr/app/prisma/migrations
    secrets:
      - database_password
      - secret_cookie_password
    security_opt:
      - no-new-privileges
  database:
    image: postgres
    environment:
      POSTGRES_USER: cryptomato
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
      POSTGRES_DB: cryptomato
    secrets:
      - database_password
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges
  worker:
    privileged: true
    build: cryptomato_worker
    networks:
      - sandbox
    volumes:
      - rpc_channels:/var/run/cryptomato
secrets:
  database_password:
    file: secrets/database_password.txt
  secret_cookie_password:
    file: secrets/secret_cookie_password.txt
volumes:
  rpc_channels: {}
  pgdata: {}
  prisma_migrations: {}
networks:
  frontend:
    internal: true
  backend:
    internal: true
  sandbox:
    internal: true
