version: '3'
services:
  web:
    build: nginx
    ports:
      - "8080:80"
    links:
      - application
    networks:
      - default
      - frontend
  application:
    build: .
    environment:
      DATABASE_URL: "postgresql://cryptomato:cryptomato@database:5432/postgres?schema=cryptomato"
    expose:
      - "3000"
    links:
      - database
    networks:
      - frontend
      - backend
    volumes:
      - rpc_channels:/var/run/cryptomato
  database:
    image: postgres
    environment:
      POSTGRES_USER: cryptomato
      POSTGRES_PASSWORD: cryptomato
      POSTGRES_DB: cryptomato
    expose:
      - "5432"
    networks:
      - backend
  worker:
    privileged: true
    build: worker
    networks:
      - sandbox
    volumes:
      - rpc_channels:/var/run/cryptomato
volumes:
  rpc_channels: {}
networks:
  frontend:
    internal: true
  backend:
    internal: true
  sandbox:
    internal: true
