# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class Experiment_APIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RPC = channel.unary_unary(
        '/Experiment_API/RPC',
        request_serializer=api__pb2.RPC_Request.SerializeToString,
        response_deserializer=api__pb2.RPC_Reply.FromString,
        )


class Experiment_APIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RPC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Experiment_APIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RPC': grpc.unary_unary_rpc_method_handler(
          servicer.RPC,
          request_deserializer=api__pb2.RPC_Request.FromString,
          response_serializer=api__pb2.RPC_Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Experiment_API', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
