# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tapi.proto\"&\n\x0bRPC_Request\x12\t\n\x01\x66\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"\x16\n\tRPC_Reply\x12\t\n\x01r\x18\x01 \x01(\t23\n\x0e\x45xperiment_API\x12!\n\x03RPC\x12\x0c.RPC_Request\x1a\n.RPC_Reply\"\x00\x62\x06proto3'
)




_RPC_REQUEST = _descriptor.Descriptor(
  name='RPC_Request',
  full_name='RPC_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='RPC_Request.f', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='RPC_Request.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=51,
)


_RPC_REPLY = _descriptor.Descriptor(
  name='RPC_Reply',
  full_name='RPC_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='RPC_Reply.r', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['RPC_Request'] = _RPC_REQUEST
DESCRIPTOR.message_types_by_name['RPC_Reply'] = _RPC_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPC_Request = _reflection.GeneratedProtocolMessageType('RPC_Request', (_message.Message,), {
  'DESCRIPTOR' : _RPC_REQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:RPC_Request)
  })
_sym_db.RegisterMessage(RPC_Request)

RPC_Reply = _reflection.GeneratedProtocolMessageType('RPC_Reply', (_message.Message,), {
  'DESCRIPTOR' : _RPC_REPLY,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:RPC_Reply)
  })
_sym_db.RegisterMessage(RPC_Reply)



_EXPERIMENT_API = _descriptor.ServiceDescriptor(
  name='Experiment_API',
  full_name='Experiment_API',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=77,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='RPC',
    full_name='Experiment_API.RPC',
    index=0,
    containing_service=None,
    input_type=_RPC_REQUEST,
    output_type=_RPC_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXPERIMENT_API)

DESCRIPTOR.services_by_name['Experiment_API'] = _EXPERIMENT_API

# @@protoc_insertion_point(module_scope)
